openapi: 3.0.3
info:
  title: Bank Argent API
  description: Documentation de l'API pour la gestion des utilisateurs et des transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/login:
    post:
      summary: Connexion de l'utilisateur
      description: Permet à un utilisateur de se connecter à son compte.
      tags:
        - Utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload'
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/profile:
    get:
      summary: Profil utilisateur
      description: Récupère les informations de profil de l'utilisateur connecté.
      tags:
        - Utilisateur
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Informations du profil récupérées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Non autorisé
        '500':
          description: Erreur interne du serveur
  /account/{accountID}/transactions:
    get:
      tags:
        - Transactions
      summary: Transactions associées à un compte
      description: Récupère toutes les transactions liées à un compte spécifique.
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID du compte
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
        '401':
          description: Non autorisé
        '404':
          description: Compte introuvable
        '500':
          description: Erreur interne du serveur
  /account/{accountID}/balance:
    get:
      tags:
        - Comptes
      summary: Solde du compte
      description: Récupère le solde actuel du compte spécifié.
      parameters:
        - name: accountID
          in: path
          required: true
          description: ID du compte
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Solde récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBalance'
        '401':
          description: Non autorisé
        '404':
          description: Compte introuvable
        '500':
          description: Erreur interne du serveur
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginPayload:
      type: object
      properties:
        email:
          type: string
          description: Adresse e-mail de l'utilisateur
        password:
          type: string
          description: Mot de passe de l'utilisateur
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Jeton d'authentification JWT
    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: ID unique de l'utilisateur
        name:
          type: string
          description: Nom complet de l'utilisateur
        email:
          type: string
          description: Adresse e-mail de l'utilisateur
    AccountBalance:
      type: object
      properties:
        accountID:
          type: string
          description: ID du compte
        balance:
          type: number
          format: double
          description: Solde actuel du compte
    TransactionResponse:
      type: object
      properties:
        transactionID:
          type: string
          description: ID de la transaction
        transactionType:
          type: string
          description: Type de la transaction (crédit ou débit)
        date:
          type: string
          format: date-time
          description: Date de la transaction
        description:
          type: string
          description: Description de la transaction
        amount:
          type: number
          format: double
          description: Montant de la transaction
        balance:
          type: number
          format: double
          description: Solde après la transaction
        category:
          type: string
          description: Catégorie de la transaction
        note:
          type: string
          description: Note associée à la transaction
